version: "3"

services:
  mariadb:
    image: mariadb
    container_name: go_service_mariadb
    restart: on-failure
    volumes:
      - ./infra/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: homestod
    networks:
      - gonet

  app:
    build:
      context: .
    volumes:
      - ./:/go/src/go_service
    image: goframework
    container_name: go_service
    restart: on-failure
    ports:
      - 4000:8000
    networks:
      - gonet

  adminer:
    image: adminer
    container_name: go_service_adminer
    ports:
      - "4001:8080"
    networks:
      - gonet

networks:
  gonet:
    driver: bridge
